services:
  backend:
    build: .
    container_name: investment-backend-container
    ports:
      - "3000:3000"
    env_file: 
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: investment-redis
    ports:
      - "6379:6379"