const lessons = [
  {
    id: "lesson-01",
    title: "Startup Foundations",
    category: "FOUNDATIONS",
    difficulty: "BEGINNER",
    estimatedMinutes: 20,
    description: "Understand what makes a startup different from a conventional small business and how founders should think about uncertainty.",
    objectives: ["Define a startup", "Understand uncertainty and experimentation", "Identify the founder's core operating questions"],
    exercise: "Write down the three biggest assumptions your startup currently depends on.",
  },
  {
    id: "lesson-02",
    title: "Problem-Solution Fit",
    category: "FOUNDATIONS",
    difficulty: "BEGINNER",
    estimatedMinutes: 25,
    description: "Learn how to distinguish a real customer problem from a solution looking for a problem.",
    objectives: ["Describe the problem clearly", "Identify affected customers", "Separate symptoms from root problems"],
    exercise: "Write a one-sentence problem statement using a specific customer segment and observable pain.",
  },
  {
    id: "lesson-03",
    title: "Startup Stages",
    category: "FOUNDATIONS",
    difficulty: "BEGINNER",
    estimatedMinutes: 20,
    description: "Map your company to a practical startup stage and understand the priorities that change as you progress.",
    objectives: ["Recognize common startup stages", "Match priorities to stage", "Avoid premature scaling"],
    exercise: "Select your current stage and list the top three outcomes you need before moving forward.",
  },
  {
    id: "lesson-04",
    title: "Founder Metrics",
    category: "FOUNDATIONS",
    difficulty: "BEGINNER",
    estimatedMinutes: 25,
    description: "Learn why a small set of operating metrics can guide better founder decisions.",
    objectives: ["Identify core startup metrics", "Distinguish leading and lagging indicators", "Create a weekly metric review"],
    exercise: "Choose five metrics that best describe the current health of your startup.",
  },
  {
    id: "lesson-05",
    title: "Hypothesis-Driven Thinking",
    category: "FOUNDATIONS",
    difficulty: "INTERMEDIATE",
    estimatedMinutes: 30,
    description: "Turn uncertain beliefs about customers, markets and products into testable hypotheses.",
    objectives: ["Write falsifiable hypotheses", "Define evidence thresholds", "Avoid confirmation bias"],
    exercise: "Convert one major assumption into a hypothesis with a measurable success criterion.",
  },
  {
    id: "lesson-06",
    title: "Customer Segmentation",
    category: "CUSTOMER",
    difficulty: "BEGINNER",
    estimatedMinutes: 25,
    description: "Learn how to divide a broad market into useful customer segments for focused decisions.",
    objectives: ["Define meaningful segments", "Compare segment attractiveness", "Choose an initial target"],
    exercise: "Create three customer segments and rank them by problem severity, ability to pay and reachability.",
  },
  {
    id: "lesson-07",
    title: "Ideal Customer Profile",
    category: "CUSTOMER",
    difficulty: "BEGINNER",
    estimatedMinutes: 25,
    description: "Build an Ideal Customer Profile that sales, marketing and product teams can consistently use.",
    objectives: ["Define ICP characteristics", "Identify buying triggers", "Document disqualifiers"],
    exercise: "Write an ICP including company/persona attributes, trigger events and buying constraints.",
  },
  {
    id: "lesson-08",
    title: "Customer Discovery",
    category: "CUSTOMER",
    difficulty: "INTERMEDIATE",
    estimatedMinutes: 30,
    description: "Learn how to conduct customer conversations that reveal behavior instead of collecting polite opinions.",
    objectives: ["Ask evidence-based questions", "Explore past behavior", "Capture recurring pain patterns"],
    exercise: "Prepare ten customer interview questions focused on recent behavior and existing alternatives.",
  },
  {
    id: "lesson-09",
    title: "Value Proposition",
    category: "CUSTOMER",
    difficulty: "BEGINNER",
    estimatedMinutes: 25,
    description: "Create a concise value proposition connecting a specific customer problem to a meaningful outcome.",
    objectives: ["State the target customer", "Express the desired outcome", "Explain the differentiating value"],
    exercise: "Write three alternative value propositions and test them against your ICP.",
  },
  {
    id: "lesson-10",
    title: "Customer Validation",
    category: "CUSTOMER",
    difficulty: "INTERMEDIATE",
    estimatedMinutes: 30,
    description: "Learn practical signals for deciding whether customer demand is strong enough to justify further investment.",
    objectives: ["Define validation signals", "Measure willingness to act", "Separate interest from commitment"],
    exercise: "Define one customer validation experiment and its minimum evidence threshold.",
  },
  {
    id: "lesson-11",
    title: "Business Model Basics",
    category: "BUSINESS_MODEL",
    difficulty: "BEGINNER",
    estimatedMinutes: 25,
    description: "Understand how customers, value creation, revenue and costs fit together in a business model.",
    objectives: ["Map key business model components", "Identify value creation", "Identify major cost drivers"],
    exercise: "Sketch your business model in one page and mark the three most uncertain assumptions.",
  },
  {
    id: "lesson-12",
    title: "Revenue Models",
    category: "BUSINESS_MODEL",
    difficulty: "BEGINNER",
    estimatedMinutes: 25,
    description: "Compare common revenue models and understand how pricing mechanics affect growth and cash flow.",
    objectives: ["Identify suitable revenue models", "Understand recurring versus transactional revenue", "Connect pricing to customer value"],
    exercise: "Compare two revenue models for your startup using predictability, margin and scalability.",
  },
  {
    id: "lesson-13",
    title: "Pricing Strategy",
    category: "BUSINESS_MODEL",
    difficulty: "INTERMEDIATE",
    estimatedMinutes: 30,
    description: "Build a pricing hypothesis based on customer value, willingness to pay and business economics.",
    objectives: ["Choose pricing dimensions", "Estimate willingness to pay", "Protect unit economics"],
    exercise: "Create three price points and document the assumptions behind each one.",
  },
  {
    id: "lesson-14",
    title: "Unit Economics",
    category: "BUSINESS_MODEL",
    difficulty: "INTERMEDIATE",
    estimatedMinutes: 30,
    description: "Understand CAC, LTV, LTV:CAC and payback period as a connected economic system.",
    objectives: ["Calculate core unit economics", "Interpret LTV:CAC", "Understand CAC payback"],
    exercise: "Calculate your current CAC, LTV, LTV:CAC and CAC payback period.",
  },
  {
    id: "lesson-15",
    title: "Business Model Stress Test",
    category: "BUSINESS_MODEL",
    difficulty: "ADVANCED",
    estimatedMinutes: 35,
    description: "Stress-test the assumptions that could make your business model fail at larger scale.",
    objectives: ["Identify economic bottlenecks", "Model downside assumptions", "Prioritize risks"],
    exercise: "Reduce conversion and gross margin assumptions and identify the point where the model becomes unsustainable.",
  },
  {
    id: "lesson-16",
    title: "Go-To-Market Strategy",
    category: "GTM",
    difficulty: "INTERMEDIATE",
    estimatedMinutes: 30,
    description: "Build a focused go-to-market strategy around audience, positioning, channels and measurable experiments.",
    objectives: ["Define GTM components", "Prioritize a target audience", "Connect channels to outcomes"],
    exercise: "Write a one-page GTM plan for your highest-priority customer segment.",
  },
  {
    id: "lesson-17",
    title: "Positioning",
    category: "GTM",
    difficulty: "INTERMEDIATE",
    estimatedMinutes: 25,
    description: "Learn how to position a startup so the right customer quickly understands the category, problem and differentiation.",
    objectives: ["Define a competitive frame", "Clarify differentiation", "Write positioning language"],
    exercise: "Write a positioning statement for your ICP and compare it with two competitors.",
  },
  {
    id: "lesson-18",
    title: "Acquisition Channels",
    category: "GTM",
    difficulty: "INTERMEDIATE",
    estimatedMinutes: 30,
    description: "Evaluate acquisition channels using reach, conversion, cost and scalability rather than intuition alone.",
    objectives: ["Compare channels", "Estimate channel economics", "Choose focused experiments"],
    exercise: "Rank five acquisition channels by reachability, expected CAC and learning speed.",
  },
  {
    id: "lesson-19",
    title: "Conversion Funnel",
    category: "GTM",
    difficulty: "INTERMEDIATE",
    estimatedMinutes: 30,
    description: "Understand how prospects move from awareness to conversion and where funnel leakage occurs.",
    objectives: ["Map funnel stages", "Measure conversion between stages", "Find the largest bottleneck"],
    exercise: "Map your funnel and calculate conversion at each stage using your latest available data.",
  },
  {
    id: "lesson-20",
    title: "Retention and Growth Loops",
    category: "GTM",
    difficulty: "ADVANCED",
    estimatedMinutes: 35,
    description: "Learn how retention and repeat behavior can create compounding growth instead of relying only on acquisition.",
    objectives: ["Understand retention", "Identify growth loops", "Connect retention to LTV"],
    exercise: "Draw one repeat-use or referral loop that could improve retention or organic acquisition.",
  },
  {
    id: "lesson-21",
    title: "Startup Financial Statements",
    category: "FINANCE",
    difficulty: "BEGINNER",
    estimatedMinutes: 30,
    description: "Learn the role of the income statement, balance sheet and cash flow statement in startup decision-making.",
    objectives: ["Understand three financial statements", "Connect profit and cash", "Identify key startup signals"],
    exercise: "Review your latest financial data and identify one important difference between profit and cash.",
  },
  {
    id: "lesson-22",
    title: "Burn Rate and Runway",
    category: "FINANCE",
    difficulty: "BEGINNER",
    estimatedMinutes: 25,
    description: "Understand monthly burn, net burn and runway so funding decisions can be made before cash becomes critical.",
    objectives: ["Calculate burn", "Calculate runway", "Set a cash warning threshold"],
    exercise: "Calculate your current runway and define the cash level at which you would start fundraising or cut costs.",
  },
  {
    id: "lesson-23",
    title: "Forecasting",
    category: "FINANCE",
    difficulty: "INTERMEDIATE",
    estimatedMinutes: 35,
    description: "Build practical forecasts using explicit assumptions for revenue, margins, costs and cash.",
    objectives: ["Create forecast assumptions", "Model revenue and costs", "Compare forecast with actuals"],
    exercise: "Create a three-scenario forecast: base, upside and downside.",
  },
  {
    id: "lesson-24",
    title: "Break-Even Analysis",
    category: "FINANCE",
    difficulty: "INTERMEDIATE",
    estimatedMinutes: 30,
    description: "Understand how pricing, gross margin and fixed costs determine the revenue required to break even.",
    objectives: ["Understand fixed and variable costs", "Calculate break-even", "Identify break-even levers"],
    exercise: "Estimate the monthly revenue or customer count required for your startup to break even.",
  },
  {
    id: "lesson-25",
    title: "Fundraising Readiness",
    category: "FINANCE",
    difficulty: "ADVANCED",
    estimatedMinutes: 35,
    description: "Learn which operating, financial and market signals investors typically need to understand before a raise.",
    objectives: ["Assess fundraising readiness", "Prepare key metrics", "Connect capital to milestones"],
    exercise: "List the next three milestones that additional capital would help you achieve and their measurable outcomes.",
  },
  {
    id: "lesson-26",
    title: "Startup Operating System",
    category: "OPERATIONS",
    difficulty: "INTERMEDIATE",
    estimatedMinutes: 30,
    description: "Create a simple operating rhythm that turns strategy into weekly execution.",
    objectives: ["Define operating cadence", "Set weekly priorities", "Review outcomes consistently"],
    exercise: "Create a weekly founder review covering metrics, priorities, risks and decisions.",
  },
  {
    id: "lesson-27",
    title: "Prioritization",
    category: "OPERATIONS",
    difficulty: "BEGINNER",
    estimatedMinutes: 25,
    description: "Learn to prioritize work by expected impact, urgency, effort and evidence.",
    objectives: ["Separate important from urgent", "Rank opportunities", "Reduce low-impact work"],
    exercise: "Rank your current top ten tasks by expected business impact and remove the bottom three.",
  },
  {
    id: "lesson-28",
    title: "Hiring and Team Design",
    category: "OPERATIONS",
    difficulty: "INTERMEDIATE",
    estimatedMinutes: 30,
    description: "Understand how to hire against business bottlenecks and design roles around measurable outcomes.",
    objectives: ["Identify hiring needs", "Define role outcomes", "Avoid premature hiring"],
    exercise: "Define the single role that would remove your most important current operational bottleneck.",
  },
  {
    id: "lesson-29",
    title: "Risk Management",
    category: "OPERATIONS",
    difficulty: "INTERMEDIATE",
    estimatedMinutes: 30,
    description: "Build a practical risk register covering financial, market, operational, technology and regulatory risks.",
    objectives: ["Identify material risks", "Assess probability and impact", "Create mitigation actions"],
    exercise: "Create a five-item risk register and assign an owner and mitigation action to each risk.",
  },
  {
    id: "lesson-30",
    title: "Scaling With Evidence",
    category: "OPERATIONS",
    difficulty: "ADVANCED",
    estimatedMinutes: 35,
    description: "Learn how to decide when a startup is ready to scale a channel, product or team based on evidence.",
    objectives: ["Define scale signals", "Distinguish repeatability from one-off success", "Set scale gates"],
    exercise: "Define three measurable conditions that must be true before you scale your highest-priority growth engine.",
  },
];

const categories = [...new Set(lessons.map((lesson) => lesson.category))].map((category) => ({
  id: category,
  name: category
    .split("_")
    .map((word) => word.charAt(0) + word.slice(1).toLowerCase())
    .join(" "),
  lessonCount: lessons.filter((lesson) => lesson.category === category).length,
}));

export const getLessons = ({ category, difficulty } = {}) => {
  return lessons.filter((lesson) => {
    const categoryMatch = !category || lesson.category === String(category).toUpperCase();
    const difficultyMatch = !difficulty || lesson.difficulty === String(difficulty).toUpperCase();
    return categoryMatch && difficultyMatch;
  });
};

export const getLessonById = (lessonId) => {
  return lessons.find((lesson) => lesson.id === lessonId) || null;
};

export const getLearningCategories = () => categories;

export const getCurriculumSummary = () => ({
  totalLessons: lessons.length,
  totalEstimatedMinutes: lessons.reduce((sum, lesson) => sum + lesson.estimatedMinutes, 0),
  categories,
  difficultyCounts: lessons.reduce((counts, lesson) => {
    counts[lesson.difficulty] = (counts[lesson.difficulty] || 0) + 1;
    return counts;
  }, {}),
});
